---
title: "Descripción"
---

# Contexto 

Además de mitigar los efectos inmediatos de la crisis generada por la
pandemia mundial del SARS-CoV-  2, una de las mayores preocupaciones a nivel
nacional es la reactivación socioeconómica las personas, las familias, las
comunidades, las regiones y el país. Ya no se trata solamente de dar un subsidio
en forma oportuna a las personas más vulnerables, sino de cómo retomar un desarrollo socio-económico sostenido en el ámbito de la sociedad como un todo.

Este es el momento más oportuno para aprovechar toda esta infraestructura
organizacional y utilizarla como un mecanismo de reactivación económica, para
amortiguar los procesos de desigualdad, eficientizar los procesos de intercambio
entre productores y consumidores, así como territorializar un desarrollo más
sostenible, más justo y amigable con el ambiente.


# Perspectiva de impacto

Ante la realidad de que muchos mercados internacionales cerrarán sus
puertas a productos nacionales, que disminuirá el consumo mundial durante un
lapso que aún no se visualiza cuánto podría demorar, eso obliga a voltear la mirada
hacia nuevos procesos de producción, distribución, mercadeo y consumo local,
donde la conectividad a nivel tecnológico también resulta de particular importancia,
para hacer más eficientes todos estos nuevos procesos.

Para ello es necesario generar orientaciones y articulaciones nacionales,
entre lo público, lo social y lo privado, pero también un modelo de gestión económica
en el ámbito puramente territorial, convirtiendo una amenaza y un impacto evidente
en nuevas oportunidades de desarrollo equilibrado e integral.